# Multi-Stage
# 1. Build the frontend
# 2. Copy the build to a nginx container

# Stage 1
FROM node:20-alpine as build
# Set the working directory
WORKDIR /app
# Copy the package.json and package-lock.json
COPY . .
# Install the dependencies
RUN npm install && npm run build

# Stage 2
# Copy the build to a nginx container
FROM nginx:alpine
# Copy the nginx config
WORKDIR /usr/share/nginx/html
# Remove the default nginx static assets
RUN rm -rf ./*
# Copy the build from the build stage
COPY --from=build /app/dist/frontend/browser .
# Copy the nginx config
RUN chown nginx:nginx /usr/share/nginx/html/*
# Expose port 2400
EXPOSE 2400
ENTRYPOINT ["nginx", "-g", "daemon off;"]