services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command:
      - npm
      - run
      - dev
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
    ports:
      - "4200:80"