FROM node:20-alpine
# Set the working directory
WORKDIR /app
# Copy the package.json and package-lock.json
copy . .
# Install the dependencies
RUN npm install
# Expose port 3000
EXPOSE 3000
# Start the server
CMD ["npm", "start"]
