FROM node:20-alpine
# Set the working directory
WORKDIR /app
# Copy the package.json and package-lock.json
COPY package*.json ./
# Install the dependencies
RUN npm install -g nodemon

RUN npm install

COPY . .